
name: Blog generator

on:
  issues:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
        
      - name: Install Python dependencies
        run: python3 -m pip install requests eventlet

      - name: Install hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.80.0/hugo_0.80.0_Linux-64bit.deb
          sudo dpkg -i hugo_0.80.0_Linux-64bit.deb

      - name: Checkout blog-hugo
        uses: actions/checkout@v2
        with:
          repository: jrdeng/blog-hugo
          submodules: recursive

      - name: Generate blog
        # TODO: the env $GITHUB_REPOSITORY contains the owner name...remove it...
        run: ./generate_and_deploy.py -o $GITHUB_ACTOR -r Playground -t ${{ secrets.GITHUB_TOKEN }} -g /usr/local/bin/hugo
