# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # trigger workflow while issues changed & push
  issues:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - run: python3 -m pip install requests eventlet
      
      - name: Install hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.80.0/hugo_0.80.0_Linux-64bit.deb
          dpkg -i hugo_0.80.0_Linux-64bit.deb
          which hugo

      - name: Checkout blog-hugo
        uses: actions/checkout@v2
        with:
          repository: jrdeng/blog-hugo
          submodules: recursive


      - name: Gen~
        run: ./generate_and_deploy.py -o $GITHUB_ACTOR -r Playground -t ${{ secrets.GITHUB_TOKEN }} -g hugo -d


      # Runs a set of commands using the runners shell
      - name: Get issues 100x1
        run: |
          echo pwd: `pwd`
          ls
          echo -------------------------------------
          curl --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'accept: application/vnd.github.v3+json' \
          --header 'per_page: 100' \
          --header 'page: 1' \
          --output 1.txt
      - name: Get issues 100x2
        run: |
          echo pwd: `pwd`
          ls
          echo -------------------------------------
          curl --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'accept: application/vnd.github.v3+json' \
          --header 'per_page: 100' \
          --header 'page: 2' \
          --output 2.txt
      - name: Diff
        run: |
          ls
          diff 1.txt 2.txt
        
