
name: Blog generator

on:
  issues:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
        
      - name: Install Python dependencies
        run: python3 -m pip install requests eventlet

      - name: Install hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.80.0/hugo_0.80.0_Linux-64bit.deb
          sudo dpkg -i hugo_0.80.0_Linux-64bit.deb

      - name: Checkout blog-hugo
        uses: actions/checkout@v2
        with:
          repository: jrdeng/blog-hugo
          path: blog-hugo
          submodules: recursive

      - name: Generate blog
        # TODO: the env $GITHUB_REPOSITORY contains the owner name...remove it...
        # TODO: SSH checkout and checkin is not allowed? use https push? (step  "Force push current repo"...
        run: |
          cd blog-hugo
          ./generate_and_deploy.py -o $GITHUB_ACTOR -r Playground -t ${{ secrets.GITHUB_TOKEN }} -g /usr/local/bin/hugo -d
          cd ..
      
      - name: Checkout current repo(the blog repo)
        uses: actions/checkout@v2
        with:
          path: current-repo

      - name: Force push current repo
        # TODO: ENV? user name and email...
        # TODO: how to push via https???
        # remember copy the .github/workflows to the new repo before force pushing
        run: |
          cd blog-hugo/public/
          cp ../../current-repo/.github . -a
          git config --global user.name "Junren Deng"
          git config --global user.email "junren.deng@gmail.com"
          git init
          git add .
          git commit -m "Auto Gen by Github Actions"
          echo ----------------------
          echo url: "https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}"
          echo ----------------------
          git push --force "https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}" master:master
          cd ../..
          
