name: test query-issues-action

on:
  push:
  workflow_dispatch:

jobs:
  test-query-issues-action:
    runs-on: ubuntu-latest
    name: A job to test query-issues-action
    steps:
      - name: use action
        id: my-action
        uses: jrdeng/query-issues-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: jrdeng/jrdeng.github.io
          author: jrdeng

      - name: store output
        run: |
          echo ${{ steps.my-action.outputs.issue_list }} >> issues.json
          pwd
          cat issues.json
          
