name: test query-issues-action

on: [push]

jobs:
  test-my-query-issues-action:
    runs-on: ubuntu-latest
    name: A job to test query-issues-action
    steps:
    - name: use action
      id: my-action
      uses: jrdeng/query-issues-action@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repo: "$GITHUB_REPOSITORY"
        author: jrdeng

    # Use the output from the step
    - name: Get the output
      run: |
        - echo "issue_list: ${{ steps.hello.outputs.issue_list }}"
        - echo "error_msg: ${{ steps.hello.outputs.error_msg }}"
